### ISSUE TITLE
[Feature Request] Display project status

### ISSUE THREAD

**Issue by jonyeezs** [brentm5/hubot-octopus-deploy#2]
Would like to be able to ask hubot to display information like what it would display on the dashboard.
ie:
project's latest, and current successful deploy on each active environment

**Comment by jonyeezs** [comment]
I've begin some work on this,
here's the proposed command: 

> hubot octo status <regex> - Returns release information of projects that matches the <regex>, in each of its environment and the latest available version

**Comment by jonyeezs** [comment]
Trying to use the beta of this, regex is annoying.

I don't want to be using regex to constantly search for something that would have dots in the name.

regex can be a powerful search term but it isn't very "dumb"-friendly.

Maybe use a levenshtein distance algorithm or just as simple string indexOf.

Here's a nice package for leven. https://www.npmjs.com/package/leven

**Comment by brentm5** [comment]
Merged and release 0.1.0
