### ISSUE TITLE
[Feature Request] - Actually deploy with a project

### ISSUE THREAD

**Issue by Woohah77** [brentm5/hubot-octopus-deploy#7]
The ability to deploy within a project that has auto-release enabled. 

1.) Get a listing of all the releases ready to be deployed to the project. hubot octo <project> list
2.) Deploy a release: hubot octo <project> <release>

**Comment by jonyeezs** [comment]
If i get you right:
eg:

project: my.awesome.service
DEV being the first environment in the cycle
and PROD the next.

```
hubot octo list my.awesome.service

1.1.2
1.1.1
1.1.0 - in DEV
1.0.0 - in PROD
```

```
hubot octo deploy my.awesome.service 1.1.2

deploying release 1.1.2 of my.awesome.service -> DEV
```

```
hubot octo deploy my.awesome.service 1.1.2 PROD`

deploying release 1.1.2 of my.awesome.service -> DEV - PROD
```

**Comment by Woohah77** [comment]
You would be correct! Right now you can set the first environment being Dev to do auto-releases. That is fine cause I do want DEV's being able to click the Deploy button themselves, however if they have the option to deploy x.x.x.x release out of slack, that would take this to the next level. This could then be extended to do the following:

We should be doing a deploy for the first step in the lifecycle and then promoting through the rest. 

hubot octo promote myawesome.service 1.1.2 PROD

**Comment by jonyeezs** [comment]
Going to start work on this 👷 

Please do not expect any dateline 👴

**Comment by jonyeezs** [comment]
@Woohah @brentm5, I've noticed that octopus project names can contain whitespaces.

This is going to be difficult to parse the project name and other args as proposed.

Would need a special delimiter to split them.

Which would you guys find better:

`hubot octo deploy my.awesome.service > 1.1.2 > PROD`

`hubot octo deploy my.awesome.service @ 1.1.2 @ PROD`

`hubot octo deploy my.awesome.service ! 1.1.2 ! PROD`

**Comment by jonyeezs** [comment]
Hi @brentm5 are you planning to publish this?

**Comment by brentm5** [comment]
Crap.  Here Ill go ahead and add you as a contributor (saw your email) also what is your NPM account?

**Comment by jonyeezs** [comment]
@brentm5 thank you!

**Comment by brentm5** [comment]
Went ahead and added you to NPM as well
